// <auto-generated />
using System;
using FieldService.Authorization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldService.Authorization.Data.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    [Migration("20260829121503_UseTimestamptz")]
    partial class UseTimestamptz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldService.Authorization.Events.PermissionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedBy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_PermissionEvents_CreatedAt");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_PermissionEvents_Type");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("idx_PermissionEvents_UserId_TenantId");

                    b.ToTable("PermissionEvents", (string)null);
                });

            modelBuilder.Entity("FieldService.Authorization.Events.RoleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_RoleEvents_CreatedAt");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("idx_RoleEvents_UserId_TenantId");

                    b.ToTable("RoleEvents", (string)null);
                });

            modelBuilder.Entity("FieldService.Authorization.Events.UserSuspensionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndedAt");

                    b.Property<Guid?>("OriginalSuspensionEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("OriginalSuspensionEventId");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("Source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_UserSuspensionEvents_CreatedAt");

                    b.HasIndex("OriginalSuspensionEventId")
                        .HasDatabaseName("idx_UserSuspensionEvents_OriginalSuspensionEventId");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_UserSuspensionEvents_Type");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("idx_UserSuspensionEvents_UserId_TenantId");

                    b.ToTable("UserSuspensionEvents", (string)null);
                });

            modelBuilder.Entity("FieldService.Authorization.Events.PermissionEvent", b =>
                {
                    b.OwnsOne("FieldService.Shared.Types.Permission", "Permission", b1 =>
                        {
                            b1.Property<Guid>("PermissionEventId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PermissionAction");

                            b1.Property<string>("Module")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PermissionModule");

                            b1.Property<string>("Resource")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PermissionResource");

                            b1.HasKey("PermissionEventId");

                            b1.ToTable("PermissionEvents");

                            b1.WithOwner()
                                .HasForeignKey("PermissionEventId");
                        });

                    b.Navigation("Permission")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
