<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FiledService.Audit</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Data\Configurations\" />
      <Folder Include="Data\Repositories\" />
      <Folder Include="Types\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FieldService.Shared\FieldService.Shared.csproj" />
      <ProjectReference Include="..\FieldService.Data\FieldService.Data.csproj" />
      <ProjectReference Include="..\FieldService.Authentication\FieldService.Authentication.csproj" />
      <ProjectReference Include="..\FieldService.Observability\FieldService.Observability.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
