<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FieldService.Broker\FieldService.Broker.csproj" />
    <ProjectReference Include="..\FieldService.Authentication\FieldService.Authentication.csproj" />
    <ProjectReference Include="..\FieldService.Cache\FieldService.Cache.csproj" />
    <ProjectReference Include="..\FieldService.Data\FieldService.Data.csproj" />
    <ProjectReference Include="..\FieldService.Shared\FieldService.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Configuration\" />
  </ItemGroup>

</Project>
