// <auto-generated />
using System;
using System.Text.Json;
using FieldService.Broker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldService.Broker.Data.Migrations
{
    [DbContext(typeof(BrokerDbContext))]
    partial class BrokerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldService.Broker.Entities.BrokerOutbox", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("MessageId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DispatchedAt");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiresAt");

                    b.Property<JsonDocument>("_message")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Message");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_BrokerOutbox_CreatedAt");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("idx_BrokerOutbox_DispatchedAt");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_BrokerOutbox_ExpiresAt");

                    b.ToTable("BrokerOutbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
