// <auto-generated />
using System;
using FieldService.Authentication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldService.Authentication.Data.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    partial class AuthenticationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldService.Authentication.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiresAt");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExternalId");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("Provider");

                    b.Property<int?>("RevocationReason")
                        .HasColumnType("integer")
                        .HasColumnName("RevocationReason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RevokedAt");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_Session_ExpiresAt");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("idx_Session_UserId_TenantId");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("FieldService.Authentication.Entities.SessionActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("Channel");

                    b.Property<string>("IpAddressHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("IpAddressHash");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("JwtId");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequestId");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("SessionId");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Timestamp");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UserAgentHash");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_SessionActivity_SessionId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_SessionActivity_Timestamp");

                    b.ToTable("SessionActivity", (string)null);
                });

            modelBuilder.Entity("FieldService.Authentication.Entities.UserAuthentication", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ExternalId");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("Provider");

                    b.HasKey("UserId");

                    b.HasIndex("ExternalId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("idx_UserAuthentication_ExternalId_Provider");

                    b.ToTable("UserAuthentication", (string)null);
                });

            modelBuilder.Entity("FieldService.Authentication.Events.UserTenantEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndedAt");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TenantName");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_UserTenantEvent_UserId");

                    b.HasIndex("UserId", "TenantId", "CreatedAt")
                        .HasDatabaseName("idx_UserTenantEvent_UserId_TenantId_CreatedAt");

                    b.ToTable("UserTenantEvent", (string)null);
                });

            modelBuilder.Entity("FieldService.Authentication.Events.UserTenantEvent", b =>
                {
                    b.HasOne("FieldService.Authentication.Entities.UserAuthentication", null)
                        .WithMany("_events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldService.Authentication.Entities.UserAuthentication", b =>
                {
                    b.Navigation("_events");
                });
#pragma warning restore 612, 618
        }
    }
}
