// <auto-generated />
using System;
using FieldService.SecretKey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldService.SecretKey.Migrations
{
    [DbContext(typeof(SecretKeyDbContext))]
    partial class SecretKeyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldService.SecretKey.Entities.SecretKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("SecretKeys");
                });

            modelBuilder.Entity("FieldService.SecretKey.Events.SecretKeyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SecretKeyId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SecretKeyId");

                    b.HasIndex("SecretKeyId", "OccurredAt");

                    b.ToTable("SecretKeyEvents");
                });

            modelBuilder.Entity("FieldService.SecretKey.Events.SecretKeyEvent", b =>
                {
                    b.HasOne("FieldService.SecretKey.Entities.SecretKey", null)
                        .WithMany("_secretKeyEvents")
                        .HasForeignKey("SecretKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldService.SecretKey.Entities.SecretKey", b =>
                {
                    b.Navigation("_secretKeyEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
