<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FieldService.Broker\FieldService.Broker.csproj" />
      <ProjectReference Include="..\FieldService.SecretKey\FieldService.SecretKey.csproj" />
      <ProjectReference Include="..\FieldService.Shared\FieldService.Shared.csproj" />
      <ProjectReference Include="..\FieldService.SignalR\FieldService.SignalR.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Cqrs\Commands\" />
      <Folder Include="Cqrs\Queries\" />
    </ItemGroup>

</Project>
