// <auto-generated />
using System;
using System.Text.Json;
using FiledService.Audit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiledService.Audit.Data.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260805165053_InitialAudit")]
    partial class InitialAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiledService.Audit.Entities.AuditAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OccurredAt");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequestId");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Resource");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("ResourceId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<JsonDocument>("_parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("Parameters");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_AuditAccesses_OccurredAt");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("idx_AuditAccesses_RequestId");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("idx_AuditAccesses_UserId_TenantId");

                    b.ToTable("AuditAccesses", (string)null);
                });

            modelBuilder.Entity("FiledService.Audit.Entities.AuditChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("OccurredAt");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("RequestId");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Resource");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ResourceId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<JsonDocument>("_changedProperties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ChangedProperties");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_AuditChanges_OccurredAt");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("idx_AuditChanges_RequestId");

                    b.HasIndex("UserId", "TenantId")
                        .HasDatabaseName("idx_AuditChanges_UserId_TenantId");

                    b.ToTable("AuditChanges", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
