// <auto-generated />
using System;
using System.Text.Json;
using FieldService.Storage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldService.Storage.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldService.Storage.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ContentType");

                    b.Property<Guid>("FileCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashMd5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StatusChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileCategoryId");

                    b.HasIndex("Status");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("StoredFiles", (string)null);
                });

            modelBuilder.Entity("FieldService.Storage.Entities.StoredFileCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("MaxSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinimumRequiredRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Version");

                    b.Property<JsonElement>("_allowedContentTypes")
                        .HasColumnType("jsonb")
                        .HasColumnName("AllowedContentTypes");

                    b.Property<JsonElement>("_allowedPermissions")
                        .HasColumnType("jsonb")
                        .HasColumnName("AllowedPermissions");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("StoredFileCategories", (string)null);
                });

            modelBuilder.Entity("FieldService.Storage.Entities.StoredFile", b =>
                {
                    b.HasOne("FieldService.Storage.Entities.StoredFileCategory", "FileCategory")
                        .WithMany()
                        .HasForeignKey("FileCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
