<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FieldService.Audit\FieldService.Audit.csproj" />
      <ProjectReference Include="..\FieldService.Authentication\FieldService.Authentication.csproj" />
      <ProjectReference Include="..\FieldService.Authorization\FieldService.Authorization.csproj" />
      <ProjectReference Include="..\FieldService.Observability\FieldService.Observability.csproj" />
      <ProjectReference Include="..\FieldService.Shared\FieldService.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
        <HintPath>..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\9.0.15\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Http.Features">
        <HintPath>..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\9.0.15\Microsoft.AspNetCore.Http.Features.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Mappers\" />
    </ItemGroup>

</Project>
