// <auto-generated />
using System;
using System.Text.Json;
using FieldService.Superset.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FieldService.Superset.Migrations
{
    [DbContext(typeof(SupersetDbContext))]
    partial class SupersetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FieldService.Superset.Entities.SupersetContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ExecutionType")
                        .HasColumnType("integer");

                    b.Property<string>("FqdnUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaxReplicas")
                        .HasColumnType("integer");

                    b.Property<int>("MinReplicas")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("SecretKeyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement?>("_executionWindow")
                        .HasColumnType("jsonb")
                        .HasColumnName("ExecutionWindow");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId")
                        .IsUnique();

                    b.ToTable("SupersetContainer", (string)null);
                });

            modelBuilder.Entity("FieldService.Superset.Entities.SupersetContainerDeploymentFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ConnectionStringId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ContainerCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomHostConnectionStringId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DataSchemaCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PersistedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SecretKeyCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SecretKeyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("SupersetTenantFlow", (string)null);
                });

            modelBuilder.Entity("FieldService.Superset.Entities.SupersetTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionStringId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StatusUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("SupersetTenant", (string)null);
                });

            modelBuilder.Entity("FieldService.Superset.Entities.SupersetTenant", b =>
                {
                    b.HasOne("FieldService.Superset.Entities.SupersetContainer", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Container");
                });
#pragma warning restore 612, 618
        }
    }
}
